"""'Init'

Revision ID: 46e4b9e8eeaf
Revises: 327853c23ca8
Create Date: 2023-06-27 23:46:16.773463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e4b9e8eeaf'
down_revision = '327853c23ca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
